### ISSUE TITLE
'NoneType' object has no attribute 'closed' - Chrome 129 - Browser opens but program crashes

### ISSUE THREAD

**Issue by ahmb** [stephanlensky/zendriver#12]
Any assistance on this would be much appreciated ! 

Get this error with Chrome 130 , the browser opens but doesnt navigate to any website and the terminal has the error output

using  python 3.10 + macOS

example being used:

```
import zendriver as uc
import asyncio

async def main():

    browser = await uc.start()
    page = await browser.get('https://www.webfunnel.ca')
    await browser.close()

if __name__ == '__main__':
    # since asyncio.run never worked (for me)
    asyncio.run(main())
```

also tried using     `browser = await uc.start(browser_args=['--headless=new'])`

```
(base) ➜  nodriver /opt/homebrew/opt/python@3.10/bin/python3.10 example1.py
Traceback (most recent call last):
  File "/Users/Newton/Documents/code/webScraping/nodriver/example1.py", line 12, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/Newton/Documents/code/webScraping/nodriver/example1.py", line 6, in main
    browser = await uc.start()
  File "/opt/homebrew/lib/python3.10/site-packages/zendriver/core/util.py", line 95, in start
    return await Browser.create(config)
  File "/opt/homebrew/lib/python3.10/site-packages/zendriver/core/browser.py", line 91, in create
    await instance.start()
  File "/opt/homebrew/lib/python3.10/site-packages/zendriver/core/browser.py", line 394, in start
    await self.connection.send(cdp.target.set_discover_targets(discover=True))
  File "/opt/homebrew/lib/python3.10/site-packages/zendriver/core/connection.py", line 414, in send
    if not self.websocket or self.closed:
  File "/opt/homebrew/lib/python3.10/site-packages/zendriver/core/connection.py", line 370, in __getattr__
    return getattr(self.target, item)
AttributeError: 'NoneType' object has no attribute 'closed'
/opt/homebrew/lib/python3.10/site-packages/zendriver/core/util.py:145: RuntimeWarning: coroutine 'Browser.stop' was never awaited
  _.stop()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by drjgouveia** [comment]
I'm currently having the exact same issue :(

**Comment by therealpurplemana** [comment]
I am seeing this on Windows machines now.  My Macintosh and Ubuntu Chrome seems okay.

**Comment by drjgouveia** [comment]
@therealpurplemana it happened to me in Ubuntu

**Comment by stephanlensky** [comment]
This is due to a breaking change in `websockets==14.0`. Thanks @rhjsong @therealpurplemana for the tip. Related nodriver issues:

- https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/2069
- https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/2075

So, the solution is to keep using `websockets==13.1` until we can fix the incompatibility.

I just released a new version of zendriver, `0.1.2` which pins `websockets<14`. If you upgrade to the latest zendriver, it should automatically downgrade your version of websockets and solve the problem.

If not, you can also try

```
pip install websockets==13.1
```

To force the downgrade.

**Comment by stephanlensky** [comment]
I created a new issue https://github.com/stephanlensky/zendriver/issues/14 for supporting the latest `websockets` version, but since pinning the older version fixes this crash I'll close this for now.

**Comment by stephanlensky** [comment]
On a related note, this made me realize my example code

```
import zendriver as uc
import asyncio

async def main():

    browser = await uc.start()
    page = await browser.get('https://www.webfunnel.ca')
    await browser.close()

if __name__ == '__main__':
    # since asyncio.run never worked (for me)
    asyncio.run(main())
```

is wrong, it should be

```
await browser.stop()
```

I just went back and fixed this in all of our docs.

**Comment by ahmb** [comment]
awesome ! thanks so much for the note. I upgraded to the latest zendriver and that fixed my issue :)
