### ISSUE TITLE
Support for websockets==14.0

### ISSUE THREAD

**Issue by stephanlensky** [stephanlensky/zendriver#14]
The latest `websockets==14.0` update has caused Zendriver to crash on browser start, see here: https://github.com/stephanlensky/zendriver/issues/12.

For now,  we have pinned an older version of `websockets`, but we should fix the incompatibility so that we can upgrade to latest.

**Comment by therealpurplemana** [comment]
It appears that this is broken again in: Version 131.0.6778.70 (Official Build) (arm64)

**Comment by stephanlensky** [comment]
@therealpurplemana are you using `websockets==13.1`? I'm pretty sure the previous issue wasn't related to the Chrome version, it was just the websockets upgrade which caused it.

**Comment by therealpurplemana** [comment]
Disregard. I rebooted and wiped my chrome data folder and it works fine.

**Comment by stephanlensky** [comment]
This is fixed in the latest version, see https://github.com/stephanlensky/zendriver/releases/tag/v0.2.1
