### ISSUE TITLE
0.22 fails to complete starting chrome on linux / ubuntu

### ISSUE THREAD

**Issue by therealpurplemana** [stephanlensky/zendriver#26]
I just tracked down a bug in my docker.  In version 0.22 with websockets==14.0, a headed Chrome instance on Ubuntu will launch; however, the instance seems to fail to resolve as the following line never executes.  On Mac OSX, the issue is not present and 0.22 works great.  Has anyone else observed this ?

Resolution:
- Pinning Zendriver @ 0.20 & Websockets==13.1 resolves the issue.

**Comment by stephanlensky** [comment]
> the instance seems to fail to resolve as the following line never executes

@therealpurplemana did you mean to paste something here? not sure which line is failing.
