### ISSUE TITLE
Proxy Usage

### ISSUE THREAD

**Issue by dinosaurtirex** [stephanlensky/zendriver#31]
How is there any way to use proxy with ZenDriver?

**Comment by slimshreydy** [comment]
@dinosaurtirex did you figure out how to do this? Still struggling here

**Comment by therealpurplemana** [comment]
code sample, won't work out of the box but should get you started:

`
    async def setup_proxy(self, username, password, tab, block_images=False):
        self.logger.info(f"PMXDriver '{self.instance_name}': Setting up proxy with username: {username}")
        try:
            self.current_tab = tab

            # Simple auth handler that just handles credentials
            def auth_challenge_handler(event):
                tab.feed_cdp(
                    cdp.fetch.continue_with_auth(
                        request_id=event.request_id,
                        auth_challenge_response=cdp.fetch.AuthChallengeResponse(
                            response="ProvideCredentials",
                            username=username,
                            password=password,
                        ),
                    )
                )

            # Simple request handler that only blocks images/fonts if needed
            async def request_paused_handler(event: cdp.fetch.RequestPaused, tab: Tab):
                request_id = event.request_id
                
                if block_images and event.resource_type in [cdp.network.ResourceType.IMAGE, cdp.network.ResourceType.FONT]:
                    tab.feed_cdp(cdp.fetch.fail_request(
                        request_id=request_id,
                        error_reason=cdp.network.ErrorReason.BLOCKED_BY_CLIENT
                    ))
                    return

                # Continue all other requests immediately
                tab.feed_cdp(cdp.fetch.continue_request(request_id=request_id))

            # Add basic handlers
            tab.add_handler(cdp.fetch.AuthRequired, auth_challenge_handler)
            tab.add_handler(cdp.fetch.RequestPaused, request_paused_handler)

            # Enable fetch with minimal patterns
            patterns = []
            if block_images:
                patterns.extend([
                    cdp.fetch.RequestPattern(
                        url_pattern="*",
                        resource_type=cdp.network.ResourceType.IMAGE,
                        request_stage=cdp.fetch.RequestStage.REQUEST
                    ),
                    cdp.fetch.RequestPattern(
                        url_pattern="*",
                        resource_type=cdp.network.ResourceType.FONT,
                        request_stage=cdp.fetch.RequestStage.REQUEST
                    )
                ])

            # Always add auth pattern
            patterns.append(
                cdp.fetch.RequestPattern(
                    url_pattern="*",
                    request_stage=cdp.fetch.RequestStage.REQUEST
                )
            )

            await tab.send(cdp.fetch.enable(
                patterns=patterns,
                handle_auth_requests=True
            ))

            #self.logger.info("Proxy setup complete")

        except Exception as e:
            self.logger.error(f"Error during proxy setup: {e}")
            raise`

**Comment by dinosaurtirex** [comment]
> code sample, might work out of the box with some minimal changes. Includes built in image and font blocking. I'd suggest building your proxy setup method and blockers for simplicity:
> 
> ```
>     async def setup_proxy(self, username, password, tab, block_images=False):
>         self.logger.info(f"PMXDriver '{self.instance_name}': Setting up proxy with username: {username}")
>         try:
>             self.current_tab = tab
> 
>             # Simple auth handler that just handles credentials
>             def auth_challenge_handler(event):
>                 tab.feed_cdp(
>                     cdp.fetch.continue_with_auth(
>                         request_id=event.request_id,
>                         auth_challenge_response=cdp.fetch.AuthChallengeResponse(
>                             response="ProvideCredentials",
>                             username=username,
>                             password=password,
>                         ),
>                     )
>                 )
> 
>             # Simple request handler that only blocks images/fonts if needed
>             async def request_paused_handler(event: cdp.fetch.RequestPaused, tab: Tab):
>                 request_id = event.request_id
>                 
>                 if block_images and event.resource_type in [cdp.network.ResourceType.IMAGE, cdp.network.ResourceType.FONT]:
>                     tab.feed_cdp(cdp.fetch.fail_request(
>                         request_id=request_id,
>                         error_reason=cdp.network.ErrorReason.BLOCKED_BY_CLIENT
>                     ))
>                     return
> 
>                 # Continue all other requests immediately
>                 tab.feed_cdp(cdp.fetch.continue_request(request_id=request_id))
> 
>             # Add basic handlers
>             tab.add_handler(cdp.fetch.AuthRequired, auth_challenge_handler)
>             tab.add_handler(cdp.fetch.RequestPaused, request_paused_handler)
> 
>             # Enable fetch with minimal patterns
>             patterns = []
>             if block_images:
>                 patterns.extend([
>                     cdp.fetch.RequestPattern(
>                         url_pattern="*",
>                         resource_type=cdp.network.ResourceType.IMAGE,
>                         request_stage=cdp.fetch.RequestStage.REQUEST
>                     ),
>                     cdp.fetch.RequestPattern(
>                         url_pattern="*",
>                         resource_type=cdp.network.ResourceType.FONT,
>                         request_stage=cdp.fetch.RequestStage.REQUEST
>                     )
>                 ])
> 
>             # Always add auth pattern
>             patterns.append(
>                 cdp.fetch.RequestPattern(
>                     url_pattern="*",
>                     request_stage=cdp.fetch.RequestStage.REQUEST
>                 )
>             )
> 
>             await tab.send(cdp.fetch.enable(
>                 patterns=patterns,
>                 handle_auth_requests=True
>             ))
> 
>             #self.logger.info("Proxy setup complete")
> 
>         except Exception as e:
>             self.logger.error(f"Error during proxy setup: {e}")
>             raise
> ```

Hello! Thanks

**Comment by dinosaurtirex** [comment]
> @dinosaurtirex did you figure out how to do this? Still struggling here with getting an auth proxy set up.

 I did it my way, just using browser extension for proxy on start.

**Comment by dinosaurtirex** [comment]
> @dinosaurtirex did you figure out how to do this? Still struggling here with getting an auth proxy set up.

background.js 

```
var config = {
    mode: "fixed_servers",
    rules: {
      singleProxy: {
        scheme: "http",
        host: "",
        port: 0000 
      },
      bypassList: ["<local>"]
    }
  };
  
  chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
  
  function callbackFn() {
    return {
      authCredentials: {
        username: "",
        password: ""
      }
    };
  }
  
  chrome.webRequest.onAuthRequired.addListener(
    callbackFn,
    {urls: ["<all_urls>"]},
    ["blocking"]
  );
 
```
manifest.json
```
{
    "manifest_version": 2,
    "name": "proxy",
    "version": "1.0",
    "permissions": [
      "proxy",
      "tabs",
      "unlimitedStorage",
      "storage",
      "<all_urls>",
      "webRequest",
      "webRequestBlocking"
    ],
    "background": {
      "scripts": ["background.js"]
    }
  }
  
```

**Comment by therealpurplemana** [comment]
Using a custom plugin is a clever idea. Thanks for posting

**Comment by cardilloscreations** [comment]
After playing around on MacOS, I was unable to do anything "easy" for setting a proxy. Not even when running an instance myself and using command line args. I actually want to use a PAC, but I couldn't even use a simple proxy. Seems like Chrome is locked down to the system settings now, which isn't ideal for scraping. It makes development overly complicated when you can't launch with different settings each time, especially since using proxies with scraping is pretty much essential.

I haven't tried the extension hack shown above, but it sure would be nice to be able to control this through this library. Seems like a primary use case for scraping at volume.

**Comment by stephanlensky** [comment]
@cardilloscreations I didn't close it, the original poster did. It looks like the easiest method is to use an extension, did you give that a try?

Another option might be to run Zendriver from within a Docker container, and then configure a proxy within the container for all outgoing traffic.

I agree though, it's unfortunate that Chrome doesn't provide an easier way to do this.

**Comment by stephanlensky** [comment]
Sorry, I missed your comment above about not trying the extension method.

I'd recommend going with that for now. Since Chrome doesn't expose a way to configure proxy settings, the only way we'd be able to support this from within the library would be using exactly the same back and shipping an extension ourselves. I think that is out of scope for this project though.

For scraping at scale, I think configuring a proxy within a Docker container is the much more maintainable approach, and it might be something we could add to our example project at [stephanlensky/zendriver-docker](https://github.com/stephanlensky/zendriver-docker).

**Comment by cardilloscreations** [comment]
@stephanlensky Ah, I see. I'm going to experiment with the extension next. The thing is, I'm trying to avoid needing too much infrastructure, etc. I was playing around with a rotating proxy, etc. But even just doing that locally it super annoying to deal with when I just want it to affect my scraper that I'm developing and not my whole system, etc. A docker solution would work also, but again, adds to the inconvenience and limits rapid development to a degree, etc.

**Comment by notsungod** [comment]
How to use proxy with headless=True ? Using the extension it still opens a window regardless.
Thanks in advance!
