### ISSUE TITLE
Support for older Python versions

### ISSUE THREAD

**Issue by therealpurplemana** [stephanlensky/zendriver#5]
My pip install zendriver isn't seeing zendriver.  Has this been pushed there yet?

```
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.12
ERROR: Could not find a version that satisfies the requirement zendriver (from versions: none)
ERROR: No matching distribution found for zendriver

[notice] A new release of pip available: 22.2.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
```

**Comment by stephanlensky** [comment]
The project currently requires Python>=3.12. Maybe if you're using an older version that could explain it?

Are you able to upgrade to the latest Python?

If not, we could probably change it to support older versions - totally didn't think about other people running older versions when I set this requirement originally.

**Comment by therealpurplemana** [comment]
Ah, that explains my other error.  I will try that now.

**Comment by stephanlensky** [comment]
Cool, let me know if it works. I'll also put supporting older versions (like nodriver) on the list in case others run into the same thing.

**Comment by therealpurplemana** [comment]
It worked and I successfully migrated to zendriver.  Thanks for making the project.

**Comment by stephanlensky** [comment]
Glad to hear it. Going to reopen in case others run into the same issue.

**Comment by stephanlensky** [comment]
The latest release supports Python >=3.10, which should hopefully be sufficient for most people.
